export default{
    title:'Product',
    name:'product',
    type:'document',
    description:"Product Table",
    fields:[
        {
            title:'title',
            name:'title',
            type:'string',
        },
        {
            title:'details',
            name:'details',
            type:'text',
        },
        {
            title:'price',
            name:'price',
            type:'number',
        },
        {
            title:'slug',
            name:'slug',
            type:'slug',
            options:{
                source:"title"
            }
        },
        {
            title:'images',
            name:'images',
            type:'array',
            of:[{
                type:"image"
            }]
        },
    ]
}